### ISSUE TITLE
Initiatives for 2023

### ISSUE THREAD

**Issue by UlisesGascon** [onebeyond/admin#20]
Please help us define new initiatives and priorities for 2023. 💪

### Current initiatives

- [ ] Repo template as baseline (Ref: #1)
- [ ] Repository migration from other orgs (Ref: #6) 

### New initiatives from #18 

__This is a list of ideas not yet agreed to become priorities in 2023, just an initial kickoff__

- [ ] At least basic Metrics (Ref: #14)
- [ ] Migrating the repos to the new org in NPM
- [ ] Define a criteria to prioritize the efforts based on the relevance of the project
- [ ] Upgrade dependencies in the projects
- [ ] Create an standarize CI for the projects (Ref: #10)
- [ ] Centralize and alert about the dependencies
- [ ] Create a Slack dedicated to Open Source and include it in the  Contribution policy.
- [ ] Add Slack notifications for vulnerabilities, activity, releases, etc...
- [ ] Strategic decisions on making the open source projects more accessible to historical maintainers (Felipe, Steve, Kevin..)

**Comment by UlisesGascon** [comment]
Added new ideas from the #32 

- [ ] We need to involve more people (let's make some noise in Slack)
- [ ] New initiative: Deprecating some packages that nobody uses?
- [ ] New initiative: Integrate changes made in forks from some clients and integrate them in the meetings too.

**Comment by UlisesGascon** [comment]
New plan from July 2023:

### Global

- [ ] Normalize repositories with Terraform and prevent the manual repository creation
- [ ] 

### Tier 1: Active and Tier 2: Maintenance

- [ ] Upgrade dependencies in the projects
- [ ] Create a standardize CI/CD process with GitHub Actions (linting, testing, deployment, license-checker, etc...)
- [ ] Add socket.dev to all the projects
- [ ] Ensure project metadata (CODEOWENERS, CoC, License...). Related: #15
- [ ] Ensure quality tools with #36
- [ ] Ensure Node.js minimal versions (16.x to 20.x)

### Tier 3: End Of Life
- [ ] Archive projects (close issues, PRs, deprecation notice, etc...)
- [ ] Remove infra associated

**Comment by UlisesGascon** [comment]
I enabled socket.dev to all the organization repositories
